[package]
name = "simdem-voter"
version = "0.1.0"
edition = "2024"

[dependencies]
lazy_static = "1.5.0"
ordinal = "0.4.0"
poise = "0.6.1"
serde = { version = "1.0.228", features = ["derive"] }
snafu = "0.8.9"
tokio = { version = "1.49.0", features = ["rt-multi-thread"] }
toml = "0.9.11"
